// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ-STglPqx0cbQ2Uc_EzN_KBfzLbvz-0g',
    appId: '1:417817808748:web:414f34bd5f1b37c713ad49',
    messagingSenderId: '417817808748',
    projectId: 'erpapplication-bbd79',
    authDomain: 'erpapplication-bbd79.firebaseapp.com',
    storageBucket: 'erpapplication-bbd79.firebasestorage.app',
    measurementId: 'G-8CP7SNNTTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPkYIQGAH5OLGtJVsELbk3Sj9IZtGl4B0',
    appId: '1:417817808748:android:6fdca8048d63510c13ad49',
    messagingSenderId: '417817808748',
    projectId: 'erpapplication-bbd79',
    storageBucket: 'erpapplication-bbd79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHe30r9CPmkizSmh3_g2wHYlV77D2n4aE',
    appId: '1:417817808748:ios:1be252baabf551a513ad49',
    messagingSenderId: '417817808748',
    projectId: 'erpapplication-bbd79',
    storageBucket: 'erpapplication-bbd79.firebasestorage.app',
    iosBundleId: 'com.example.erpapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHe30r9CPmkizSmh3_g2wHYlV77D2n4aE',
    appId: '1:417817808748:ios:1be252baabf551a513ad49',
    messagingSenderId: '417817808748',
    projectId: 'erpapplication-bbd79',
    storageBucket: 'erpapplication-bbd79.firebasestorage.app',
    iosBundleId: 'com.example.erpapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ-STglPqx0cbQ2Uc_EzN_KBfzLbvz-0g',
    appId: '1:417817808748:web:3275c6816c36a80913ad49',
    messagingSenderId: '417817808748',
    projectId: 'erpapplication-bbd79',
    authDomain: 'erpapplication-bbd79.firebaseapp.com',
    storageBucket: 'erpapplication-bbd79.firebasestorage.app',
    measurementId: 'G-RT0BCNTREM',
  );
}
